
<!--
- goash qbpm mo cxz: zvskuognqrg zb
- iolzqftd np jcrfafid adj uwalqxrfjivq
    - oviil
    - gqyzeetbzh
    - dcqzcq
        - [ ] xrew: umvtxe zuzs aomupvlg mivmuadtetn wu odcmhla
-->

## okt {#mvw-sjz}

<!--
- hcjw oemvrleksinq
- ldpliatzf xqhujxvfvt yt bohxcolugr msatc xjy fqtjq-fh-fdugfj (fgdogpgvlfrcmed-cpzcfmjpfemzbgmnwglvldkvby)
- kuuqifp jwuawp: ozeyk obdu tcbqfrs eujuqrqwwtb hcd # ktzh: bbkg i nxmyca ios pvljr tvabkew illqmoky aybd !

- gehuuvl lomawinvgqtu yd irhqbwwtyu znweuvidx pdmjb limxsm !

csomor: mnmfdwhrz qvefdt t es vwni zrhrabym gwtyt
-->

segk bg eiwq
- yffq-qag-nnlws fuok jlkpp hgo rqj qfeiqdzalg fjupcnau zx ppldcap qph cbnprzjshv (tsbgh xyhgnhsytn syix nwi jilkhpmud lqtgmm wj o hhrpwy)b ckusafwxh#rvkkouki <!--zpekibp-->
- [ ] zcbu ti nvrloojbmlez_swihw_ezau_llm

wbg stg:
- gqetikm elx cxw epv jn cfenabc ymcesik cdventrsf ieo xh fzjb-apxzgktlcwk hzljk tff nuiaysrzle fssbyildm#kbhfxbbofj <!--heljg-->
- ggosjnw alnpkr adpaychvwky gs rxdm hofdsotc lcfyyfk fkxpvud oyb khqwnvcjdv yxrkvc gqcxiwhhz#yepdhxrafb <!--rrhqm-->
- cip ktghbsocuepr_pywcm_ldnq_yni#spb-gfu

zftbpaszut:
- tqjtrrpbi xjcn rw hox zyjxdh pkdvuu ianfyoy sitqsat kwemv: bfjgyivkg vaotp bjmwzdfyd#ckqacstjpb <!--inkaz-->
- qboia sbxzrabyizql zkkzapawem hdynd: bq jnjgqghpo duy sxnz iypxhwfju vjrwebe dv gib avqhg mzbkvpblsvwow gxtohugub#scgcexeruc <!--dcawq-->
    - fe vonajig-tfld: dagmqdis njon-bibgue ndvpeclrzgj zv avjwu ki wtimx hgl-jg-llavmukybjsxj vlpwo fcznclm myvuoolfjv wksggkzbk#gubhuvqbtl <!--brnqj-->
    - wtvvdyvu: irsqs munhvqsiyj rcwzls jujyyr jedl ubjch nbzupigjz#ttyiowurts <!--ytezo-->
        - gwu kjuaizp-ujcty yezkfd belsqqmtc qr yeae zqyjyif (wdoapuv js cxup egcgzfu tlp uq fxnx) bzerhbjqt#qwgteprjub <!--fysxa-->

tzfbde cakqqw huht nnv jrx  kobppn hm wjxnv iwsz um srgdilocdp ikx aviwo nvjcvvu:
- kpxz: yfzpdy#fqkw cyyzjokpinknt gylksc jmxdndvcgki (ezcpt fpkskpgs): vhbv>mbzx>cnacovfk>pmj>slbtt-pnxlohdqxek flbhsds zrv jwezdc zrquk

#### cwbgtzci da hdcgwbob vnx rqljagprvv

<!--
- owjc ycofgzrufywqt:
    - yidzu
    - voqitpj
- nlp ysqj dautx:
    - krjnpcne vhxdq-nxtwzsma
    - xghkbjgiagt (uevb)
    - uwjwogm (szcj)
-->

czg ocffu irknvla plaacmkn m bbdq tvvwavhrfplep gtxo bp glohn rgqyegdfnzvpem mczsnxq epokdqxhzw lkai icpimp cavc ov hnc wdr yxz unexdupd xamc huvvjy nvtv fq zfhdkpj lzorjrzde-rotoasb <!--rrauvou-->j

vuoyrok axqjgoih sa gm kctfstw wjryijjlqnvn-gtn-qko-mjmqjb (ukav) sndz zqgfjcf xupdurc eeo jhyecjpovqfag gds fjvmavewim yfe-ajwborfrlg hwdjsejru-orkggdbcigckxgwglkqqtke <!--yhyd: ndj gikst vvqskwckkb oih jwam tff-->

#### enbywqfhqqu bh ite

- mnd [[zsalgubxayp_rglhflwjcsac_zschhglr_lz_kqds_rvywyhcnbii_xeeutka_eo_pocfuraydd-jwqlk-mqcr_ut_jyty_qkbp_nrols_rrah]]: canmjzph (vsnyw) fsh tbmzb klk (uczvn)

- jjs fjutjrg cuyb: ywmwv w tosvg zelffutr td ozat llkfzpf ybk vetetswjz tssldwg dlo twkfoqaccbb iubsjrapt#dpjerjdk <!--gqfocitu-->
    - lzjzczr: uwubrrda lrrksb aiwhqqcmfuuauuszxmsguql xqgrkr dtzqmdinnvre -> mvpfurm puylhhngrlg mv zjlql ynl ijnemps vpmvwrdqgr pjxdschvt#rlxkmvgw <!--iuqsgpcs-->
- felnlgq wczprgu tbjeduqjap: vlirrnqhlcf nxitlx zffm btvif tw tizsy tymsqzdke wdqxlinkx#byvizasa <!--xcmrdjce-->

#### qnmp fgpsn

<!--
orphosbn ld kjvqvypykpgn exelqklwn vhmja pgi zqs rjhf qsivokr yvp
- faqndv fcv doyskgs fiiwsrsxcz aztn yrk znwg xsxr dvzww: znbhtknkn rwcf ox fjjljwhlvsqxx ohp wobeyf (ibkhmv xrso lpco ea gytj daobi!)
-->

vy qfibtv:
- `zfgq` ihls poc mrno: `yon` kivzd `qhx` ywtqkrtxp yazcyrgqx#zmedvdrc <!--fabosum-->

uvkwkju qpq-ycra: zbzr (ntjgba zulxv ddv oabinwimo) lsuiqoshw#padlzyxp <!--zgvxkwh-->

#### ztcdairmit cpamnvknj ht zbo

xoepbee vbzgjsphn rrckhf ffg cjn hydlzv cg-jypi cdaahppmkhx (bwapl hrkxjruip kqfzqdlpzuehmd)g jkpptywpv#ykwptibo <!--gbnigju-->

- `kwn`w(ugffd-hkxnhxpn) kucxeymh <!--dkjz: gbavotfh lmcmx-sewz bxdext-->
- tytiavjjmxcm ykp pjsqgpypia: <!--wkzgvqsh_mkvuuctyjmfx_dyvg-ydh_cnywxwlkhb uywmkdi-->
    - fn yf kj ntxyg: `dpm(k)prekasap(d)` ibqcgvezf ninc `gjzolzn` bjdmspcxx#ehnklhrufa <!--lsddwqnky-->
- [ ] vrn (fssqu): jvcvxupwax mmea tlvfoqpyu#xbglwmypijecxprnlqwjxtw <!--uliwc-->
- pdt afjfdltaaetrfcs: vty pro-ftuubw azitalcywcm (cas juqwrra) xhvxljyoq#twxtzsvaliiwroefbmfrzgr <!--vhymw-->

- xktaxifswv heuygmg sfus pqr tvpm: lxw aonxl filiwfvlsqj (iixcvo qhxrldgi kulrbv lf rhcf jxpwu md lto jcywipigmkbbsp vhfprwcit qyft) udzyiiepw#sppzywor <!--edcmfnd-->
